services:
- docker
script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- docker build -t alpin3/ulx3s-dev:$BRANCH .
- docker login -u="$DOCKER_HUB_LOGIN" -p="$DOCKER_HUB_PASSWORD"
- docker push alpin3/ulx3s-dev:$BRANCH
- docker tag alpin3/ulx3s-dev:$BRANCH alpin3/ulx3s-dev:$DOCKER_TAG
- docker push alpin3/ulx3s-dev:$DOCKER_TAG
